print("Adınız nedir?")
ad = input()
print("Soyadınız nedir?")
soyad = input()
print("Yaşınız nedir?")
yas =  input()
print("Doğduğunuz gün nedir?")
dogumGun = input()
print("Doğduğunuz ay nedir?")
dogumAy = input()
print("Doğum yılınız nedir?")
dogumYıl = input()
print("Mesleğiniz nedir?")
meslek = input()
print("Kaç kardeşiniz var?")
kardesSayi = input()
if not kardesSayi == "0":
    print("Kardeşlerinizin birinin adı nedir?")
    kardesAd = input()
print("Ad =",ad)
print("Soyad =",soyad)
print("Yaş =",yas)
print("Doğum Günü =",dogumGun)
print("Doğum Ayı =",dogumAy)
print("Doğum Yılı =",dogumYıl)
print("Meslek =",meslek)
print("Kardeş sayısı =",kardesSayi)
if not kardesSayi == "0":print("Kardeş adı =",kardesAd)
