vize = int(input("Vize notunuzu giriniz"))
odev1 = int(input("1. Ödev notunuzu giriniz"))
odev2 = int(input("2. Ödev notunuzu giriniz"))
araSinav = int(input("Ara sınav notunuzu giriniz"))
finalSinav = int(input("Final notunuzu giriniz"))
sonPuan = ((vize * 20) / 100) + ((odev1 * 10) / 100) + ((odev2 * 10) / 100) + ((araSinav * 10) / 100) + ((finalSinav * 50) / 100)
if sonPuan >= 90:print("AA")
elif sonPuan >= 90:print("AA")
elif sonPuan >= 80:print("BA")
elif sonPuan >= 70:print("BB")
elif sonPuan >= 60:print("CB")
elif sonPuan >= 50:print("CC")
elif sonPuan >= 40:print("DC")
elif sonPuan >= 30:print("DD")
elif sonPuan >= 20:print("FD")
else:print("FF")

